sudo: required

services:
  - docker

before_install:
  - docker build  -t cloudpg07/complex-app -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cloudpg07/complex-app npm test -- --coverage

after_success:
  - docker build -t cloudpg07/multi-client ./client
  - docker build -t cloudpg07/multi-server ./server
  - docker build -t cloudpg07/multi-nginx ./nginx
  - docker build -t cloudpg07/multi-worker ./worker
  # Login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take all above images and push them to docker hub
  - docker push cloudpg07/multi-client
  - docker push cloudpg07/multi-server
  - docker push cloudpg07/multi-nginx
  - docker push cloudpg07/multi-worker

